### ISSUE TITLE
充值界面404

### ISSUE THREAD

**Issue by GoddessGargoyle** [Steady-WJ/cdnfly-kaixin#1]
充值界面
/console/index.html#/account/balance/
提示 请求视图文件异常，状态：404

**Comment by xuelang113** [comment]
还有：
/console/index.html#/account/balance/
console/index.html#/account/order/
/console/index.html#/account/log/login
/console/index.html#/account/log/op

**Comment by secut** [comment]
文件目录：master/panel/src/views/account
解压master安装包，进到上面那个目录了去。删除balance log order这三个文件
/opt/cdnfly/master/panel/src/views/finance/balance/  ------>  opt/cdnfly/master/panel/src/views/account/balance 
/opt/cdnfly/master/panel/src/views/system/log/  ------->  opt/cdnfly/master/panel/src/views/account/log 
/opt/cdnfly/master/panel/src/views/finance/order/  ------>  opt/cdnfly/master/panel/src/views/account/order 
新建这3个目录的软连接，新建软连接一定要是目录软连接，不是目录下面的文件，或者直接把这三个目录复制过去也行，如果没有安装则需要重新打包。
